import {
  BarChartOutlined,
  DollarOutlined,
  ShopOutlined,
  InboxOutlined,
  ShoppingCartOutlined,
  AuditOutlined,
  FundOutlined,
  ContainerOutlined,
  TeamOutlined,
  UserOutlined,
  AppstoreOutlined,
  SwapOutlined,
  FunnelPlotOutlined,
  RollbackOutlined,
  FileTextOutlined,
  ClockCircleOutlined,
  SolutionOutlined,
  CreditCardOutlined,
  TrophyOutlined,
  ToolOutlined,
  AccountBookOutlined,
  SyncOutlined,
  StopOutlined,
  AlertOutlined,
  ReconciliationOutlined,
  CalculatorOutlined,
  SafetyCertificateOutlined,
  FileProtectOutlined,
  FileDoneOutlined,
  PercentageOutlined,
  GoldOutlined,
  LineChartOutlined,
  IdcardOutlined,
  FieldTimeOutlined,
  StarOutlined,
  SearchOutlined,
} from '@ant-design/icons'
import type { ReactNode } from 'react'

const ICON_MAP: Record<string, React.ComponentType<{ style?: React.CSSProperties }>> = {
  BarChartOutlined,
  DollarOutlined,
  ShopOutlined,
  InboxOutlined,
  ShoppingCartOutlined,
  AuditOutlined,
  FundOutlined,
  ContainerOutlined,
  TeamOutlined,
  UserOutlined,
  AppstoreOutlined,
  SwapOutlined,
  FunnelPlotOutlined,
  RollbackOutlined,
  FileTextOutlined,
  ClockCircleOutlined,
  SolutionOutlined,
  CreditCardOutlined,
  TrophyOutlined,
  ToolOutlined,
  AccountBookOutlined,
  SyncOutlined,
  StopOutlined,
  AlertOutlined,
  ReconciliationOutlined,
  CalculatorOutlined,
  SafetyCertificateOutlined,
  FileProtectOutlined,
  FileDoneOutlined,
  PercentageOutlined,
  GoldOutlined,
  LineChartOutlined,
  IdcardOutlined,
  FieldTimeOutlined,
  StarOutlined,
  SearchOutlined,
}

export function resolveIcon(name: string, style?: React.CSSProperties): ReactNode {
  const Icon = ICON_MAP[name]
  if (!Icon) return null
  return <Icon style={style} />
}
